---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache2 webserver
      yum: name=httpd state=present
    - name: Ensure apache is up and running
      service: name=httpd state=started enabled=yes
    